import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mainScroll: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  dashboardContainer: {
    paddingBottom: 40,
  },
  dashboardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 54,
    paddingBottom: 16,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarContainer: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#f0fdf4',
    borderWidth: 2,
    borderColor: '#15803d',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    color: '#15803d',
    fontSize: 16,
    fontWeight: '700',
  },
  headerTextContainer: {
    flexDirection: 'column',
  },
  dashboardGreeting: {
    fontSize: 14,
    color: '#64748b',
    fontWeight: '500',
  },
  dashboardUserName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: -0.3,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  circleButtonBlack: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#0f172a',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  circleButtonWhite: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeIndicator: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ea580c',
    borderWidth: 1.5,
    borderColor: '#ffffff',
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 24,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: -0.3,
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#15803d',
  },
  categoryScroll: {
    paddingLeft: 20,
    marginBottom: 16,
  },
  categoryScrollContent: {
    paddingRight: 40,
    gap: 8,
  },
  categoryPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
  },
  categoryPillActive: {
    backgroundColor: '#0f172a',
  },
  categoryPillText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
  },
  categoryPillTextActive: {
    color: '#ffffff',
  },
  overviewGrid: {
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 20,
  },
  bigOverviewCard: {
    borderRadius: 20,
    padding: 20,
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: 140,
    shadowColor: '#15803d',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  bigCardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
    opacity: 0.9,
  },
  whiteArrowCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bigCardValueContainer: {
    marginTop: 16,
  },
  bigCardValue: {
    fontSize: 48,
    fontWeight: '800',
    color: '#ffffff',
    lineHeight: 52,
  },
  bigCardSub: {
    fontSize: 14,
    color: '#ffffff',
    opacity: 0.85,
    marginTop: 4,
    fontWeight: '500',
  },
  smallCardsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  smallOverviewCard: {
    flex: 1,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    padding: 16,
    minHeight: 120,
    justifyContent: 'space-between',
  },
  primaryArrowCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f0fdf4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  warningArrowCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#fffbeb',
    justifyContent: 'center',
    alignItems: 'center',
  },
  smallCardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
  },
  smallCardValueContainer: {
    marginTop: 8,
  },
  smallCardValue: {
    fontSize: 32,
    fontWeight: '800',
    color: '#0f172a',
  },
  smallCardSub: {
    fontSize: 12,
    color: '#94a3b8',
    marginTop: 2,
    fontWeight: '500',
  },
  productivityRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 20,
  },
  productivityCard: {
    flex: 1,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    padding: 16,
    minHeight: 160,
  },
  productivityCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 12,
  },
  gaugeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  gaugeSub: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 6,
  },
  chartContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    flex: 1,
    paddingTop: 10,
    paddingHorizontal: 4,
  },
  chartBarGroup: {
    alignItems: 'center',
    gap: 4,
  },
  chartBar: {
    width: 14,
    borderRadius: 4,
  },
  chartBarLabel: {
    fontSize: 10,
    color: '#94a3b8',
    fontWeight: '600',
  },
  machinesSection: {
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 24,
  },
  machineCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    padding: 16,
    gap: 12,
  },
  machineCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  machineMeta: {
    flex: 1,
    gap: 2,
  },
  machineName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: -0.2,
  },
  machineCategory: {
    fontSize: 12,
    fontWeight: '500',
    color: '#64748b',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  machineMetricsRow: {
    flexDirection: 'row',
    gap: 16,
    borderTopWidth: 1,
    borderColor: '#f1f5f9',
    paddingTop: 12,
  },
  machineMetric: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  machineMetricText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  incidentsSection: {
    paddingHorizontal: 20,
    gap: 12,
  },
  incidentListItem: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  incidentCategoryIndicator: {
    width: 4,
    height: '100%',
    borderRadius: 2,
  },
  incidentListBody: {
    flex: 1,
    gap: 2,
  },
  incidentListTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0f172a',
  },
  incidentListSub: {
    fontSize: 11,
    fontWeight: '500',
    color: '#64748b',
  },
  severityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  severityBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  // Custom Gauge Elements
  customGaugeWrapper: {
    width: 100,
    height: 50,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  customGaugeBg: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 12,
    borderColor: '#f1f5f9',
    position: 'absolute',
    bottom: -50,
  },
  customGaugeFill: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 12,
    borderColor: '#15803d',
    position: 'absolute',
    bottom: -50,
    transform: [{ rotate: '45deg' }], // Simulated fill angle
  },
  gaugeValueText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
    position: 'absolute',
    bottom: 2,
  },
});
