import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mainScroll: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  reportScrollContainer: {
    paddingHorizontal: 24,
    paddingTop: 54,
    paddingBottom: 48,
    gap: 20,
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  backBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  detailTitleText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
  },
  reportScreenHeader: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  reportScreenDesc: {
    fontSize: 14,
    fontWeight: '500',
    color: '#64748b',
    lineHeight: 20,
    marginBottom: 4,
  },
  formSection: {
    gap: 8,
    width: '100%',
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
  },
  photoUploadBox: {
    height: 160,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#cbd5e1',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: '#f8fafc',
  },
  photoUploadPlaceholder: {
    alignItems: 'center',
    gap: 8,
    padding: 16,
  },
  photoUploadMainText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
  },
  photoUploadSubText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#64748b',
  },
  photoPreviewWrapper: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoPreview: {
    width: '100%',
    height: '100%',
    opacity: 0.8,
  },
  photoBadgeOver: {
    position: 'absolute',
    backgroundColor: '#15803d',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  photoBadgeText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
  },
  formTextInput: {
    height: 52,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 14,
    fontWeight: '500',
    color: '#0f172a',
    backgroundColor: '#ffffff',
  },
  severitySegmentRow: {
    flexDirection: 'row',
    gap: 10,
  },
  severitySegment: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  severityText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
  },
  formTextArea: {
    height: 120,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 14,
    fontWeight: '500',
    color: '#0f172a',
    backgroundColor: '#ffffff',
    textAlignVertical: 'top',
  },
  submitReportBtn: {
    height: 52,
    borderRadius: 12,
    backgroundColor: '#15803d',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    shadowColor: '#15803d',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  submitReportBtnText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  successOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 24,
  },
  successBox: {
    width: '100%',
    maxWidth: 320,
    borderWidth: 1.5,
    borderColor: '#16a34a',
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    gap: 16,
    backgroundColor: '#ffffff',
    shadowColor: '#16a34a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 4,
  },
  successIconBox: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#16a34a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  successTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
  },
  successDesc: {
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 22,
    fontWeight: '500',
  },
});
