import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mainScroll: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: -0.2,
  },
  statusBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 54,
    paddingBottom: 16,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  backBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  detailTitleText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
  },
  detailContentContainer: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    gap: 20,
    paddingBottom: 48,
  },
  machineBannerCard: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 20,
    padding: 20,
    gap: 14,
    backgroundColor: '#ffffff',
  },
  bannerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  machineMeta: {
    flex: 1,
    gap: 2,
  },
  bannerName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: -0.3,
  },
  bannerMeta: {
    fontSize: 13,
    fontWeight: '500',
    color: '#64748b',
  },
  statusBadgeLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  healthIndicatorText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#64748b',
  },
  healthProgressBarBg: {
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
  },
  healthProgressBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  sensorsGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  sensorDialCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#ffffff',
  },
  sensorValText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
  },
  sensorLabelText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#64748b',
    textAlign: 'center',
  },
  statusIndicatorLabel: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginTop: 4,
  },
  trendsChartCard: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 20,
    padding: 20,
    gap: 14,
    backgroundColor: '#ffffff',
  },
  chartCardTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0f172a',
  },
  chartCardSubtitle: {
    fontSize: 12,
    fontWeight: '500',
    color: '#64748b',
    marginTop: -8,
  },
  chartVisualWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 100,
    marginTop: 8,
    gap: 8,
  },
  chartYAxis: {
    justifyContent: 'space-between',
    height: '100%',
    paddingRight: 6,
  },
  yText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94a3b8',
  },
  chartBarsContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: '100%',
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#e2e8f0',
    paddingLeft: 8,
    paddingBottom: 2,
  },
  chartBarCol: {
    width: '7%',
    borderRadius: 3,
  },
  chartXLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 24,
    marginTop: 4,
  },
  xText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94a3b8',
  },
  machineTableCard: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 20,
    padding: 20,
    gap: 14,
    backgroundColor: '#ffffff',
  },
  tableHeaderTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0f172a',
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  tableLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
  },
  tableValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0f172a',
  },
  timelineCard: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 20,
    padding: 20,
    gap: 14,
    backgroundColor: '#ffffff',
  },
  timelineHeaderTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0f172a',
  },
  timelineList: {
    gap: 20,
    marginTop: 4,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineIndicators: {
    alignItems: 'center',
    width: 12,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    zIndex: 2,
  },
  timelineLine: {
    width: 2,
    position: 'absolute',
    top: 10,
    bottom: -20,
    zIndex: 1,
  },
  timelineBody: {
    flex: 1,
    gap: 4,
  },
  timelineTimeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94a3b8',
  },
  timelineTitleText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0f172a',
  },
  timelineDescText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#64748b',
    lineHeight: 16,
  },
});
